// <auto-generated />
using System;
using ContractsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractsService.Migrations
{
    [DbContext(typeof(ContractsDbContext))]
<<<<<<<< HEAD:servidor/servicios/API_Contracts/ContractsService/Migrations/20260509164709_InitialCreate.Designer.cs
    [Migration("20260509164709_InitialCreate")]
========
    [Migration("20260508153023_InitialCreate")]
>>>>>>>> 2091ac394baf4f9e506f285c8fe6f16b2f139557:servidor/servicios/API_Contracts/ContractsService/Migrations/20260508153023_InitialCreate.Designer.cs
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<<< HEAD:servidor/servicios/API_Contracts/ContractsService/Migrations/20260509164709_InitialCreate.Designer.cs
========
            modelBuilder.Entity("ContractsService.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

>>>>>>>> 2091ac394baf4f9e506f285c8fe6f16b2f139557:servidor/servicios/API_Contracts/ContractsService/Migrations/20260508153023_InitialCreate.Designer.cs
            modelBuilder.Entity("ContractsService.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<<< HEAD:servidor/servicios/API_Contracts/ContractsService/Migrations/20260509164709_InitialCreate.Designer.cs
                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

========
>>>>>>>> 2091ac394baf4f9e506f285c8fe6f16b2f139557:servidor/servicios/API_Contracts/ContractsService/Migrations/20260508153023_InitialCreate.Designer.cs
                    b.Property<string>("ClientDeclaraciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

<<<<<<<< HEAD:servidor/servicios/API_Contracts/ContractsService/Migrations/20260509164709_InitialCreate.Designer.cs
                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

========
>>>>>>>> 2091ac394baf4f9e506f285c8fe6f16b2f139557:servidor/servicios/API_Contracts/ContractsService/Migrations/20260508153023_InitialCreate.Designer.cs
                    b.Property<string>("ClientObjetoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:servidor/servicios/API_Contracts/ContractsService/Migrations/20260509164709_InitialCreate.Designer.cs
                    b.Property<string>("ClientRfc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

========
>>>>>>>> 2091ac394baf4f9e506f285c8fe6f16b2f139557:servidor/servicios/API_Contracts/ContractsService/Migrations/20260508153023_InitialCreate.Designer.cs
                    b.Property<string>("ContractDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Representative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalBasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("ContractsService.Models.ContractExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractExtras");
                });

            modelBuilder.Entity("ContractsService.Models.ContractPaymentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractPayments");
                });

            modelBuilder.Entity("ContractsService.Models.ContractServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:servidor/servicios/API_Contracts/ContractsService/Migrations/20260509164709_InitialCreate.Designer.cs
                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

========
>>>>>>>> 2091ac394baf4f9e506f285c8fe6f16b2f139557:servidor/servicios/API_Contracts/ContractsService/Migrations/20260508153023_InitialCreate.Designer.cs
                    b.Property<int>("Technicians")
                        .HasColumnType("int");

                    b.Property<int>("Vehicles")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractServices");
                });

<<<<<<<< HEAD:servidor/servicios/API_Contracts/ContractsService/Migrations/20260509164709_InitialCreate.Designer.cs
            modelBuilder.Entity("ContractsService.Models.Quotation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientRfc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicesRawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Quotations");
                });

========
>>>>>>>> 2091ac394baf4f9e506f285c8fe6f16b2f139557:servidor/servicios/API_Contracts/ContractsService/Migrations/20260508153023_InitialCreate.Designer.cs
            modelBuilder.Entity("ContractsService.Models.ContractExtra", b =>
                {
                    b.HasOne("ContractsService.Models.Contract", null)
                        .WithMany("Extras")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractsService.Models.ContractPaymentItem", b =>
                {
                    b.HasOne("ContractsService.Models.Contract", null)
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractsService.Models.ContractServiceItem", b =>
                {
                    b.HasOne("ContractsService.Models.Contract", null)
                        .WithMany("Services")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractsService.Models.Contract", b =>
                {
                    b.Navigation("Extras");

                    b.Navigation("Payments");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
