"""crear tabla clientes

Revision ID: 4c787ac713ce
Revises: 
Create Date: 2026-04-10 13:58:53.653437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '4c787ac713ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('registerDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('rfc', sa.String(length=100), nullable=True),
    sa.Column('urlSatCertificate', sa.String(length=100), nullable=True),
    sa.Column('semarnatNum', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('activo', 'inactivo', name='statusenum'), nullable=False),
    sa.Column('idUser', UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
